version: 'v2.20.2-desktop.1'

services:
  mysqlDB:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      #volumes:
      #- /d97e2f16f8136bbbcac738239ddbeb868e406de1f2ee4f6c98cdd79b382452df.tar.zst